---
services:
  database.postgres:
    image: pgautoupgrade/pgautoupgrade:18-alpine@sha256:38bab947a327879bb36608cf9940a243cdcd1d2cbb947465b753a567c7021660
    container_name: healthchecks_postgres
    volumes:
      - /opt/docker/healthchecks/db/:/var/lib/postgresql/
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_DB: ${PG_DB:-hc}
    networks:
      - db
    extends:
      file: ../../_common/base.yaml
      service: x-postgres

  service.healthchecks:
    image: healthchecks/healthchecks:v4.4@sha256:aa08a61b0dcfd83f1332eab195d5cec1b595ae076eb8388cadf8a3d597114f9b
    container_name: healthchecks
    depends_on:
      database.postgres:
        condition: service_healthy
    volumes:
      - /opt/docker/healthchecks/web/logo.png:/static/img/logo.png
    environment:
      DB: postgres
      DB_HOST: database.postgres
      DB_NAME: ${PG_DB:-hc}
      DB_USER: ${PG_USER:-postgres}
      DB_PASSWORD: ${PG_PASS:?database password required}
      DB_PORT: 5432
    env_file: .env
    networks:
      - db
      - pangolin
    command: bash -c 'while !</dev/tcp/$${DB_HOST}/$${DB_PORT}; do sleep 1; done; uwsgi /opt/healthchecks/docker/uwsgi.ini'
    expose:
      - '8000'
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

networks:
  db:
    internal: true
  pangolin:
    external: true
    name: pangolin
