---
services:
  api:
    image: ghcr.io/danny-avila/librechat:v0.8.7@sha256:c5db3331b845e1f289f8d04c0c77936c4bbe372f76730a804abc1c37e44d23a9
    container_name: LibreChat
    depends_on:
      - mongodb
      - rag-api
    volumes:
      # - /opt/docker/librechat/.env:/app/.env
      - /opt/docker/librechat/images/:/app/client/public/images/
      - /opt/docker/librechat/uploads/:/app/uploads/
      - /opt/docker/librechat/logs/:/app/api/logs/
    environment:
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag-api:${RAG_PORT:-8000}
    env_file: .env
    ports:
      - '${PORT}:${PORT}'
    networks:
      default:
      database:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: 1000:1000
    deploy:
      resources:
        limits:
          memory: ${LIBRECHAT_API_MEM_LIMIT:-2g}
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

  db-backup:
    image: tiredofit/db-backup:4.1.100@sha256:78e3cb669ee9648c1a4ab7e8421c6e89d01b659bfa5963f7611a2347b2009eab
    container_name: LibreChat_db-backup
    depends_on:
      - mongodb
      - vectordb
    volumes:
      - /opt/docker/librechat/backup/:/backup/
    environment:
      DB01_TYPE: mongo
      DB01_HOST: mongodb
      DB02_TYPE: pgsql
      DB02_HOST: vectordb
      DB02_NAME: ${POSTGRES_DB:?database name required}
      DB02_USER: ${POSTGRES_USER:?database username required}
      DB02_PASS: ${POSTGRES_PASSWORD:?database password required}
      CONTAINER_ENABLE_MONITORING: FALSE
    networks:
      database:
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

  meilisearch:
    image: getmeili/meilisearch:v1.53.1@sha256:8d6643d86d71fad6ad3cba92cde7ccfce9e4d6c384bda67598eb553571c32431
    container_name: LibreChat_meilisearch
    volumes:
      - /opt/docker/librechat/meilisearch/:/meili_data/
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:?Meilisearch master key required}
      MEILI_NO_ANALYTICS: "true"
      MEILI_UPGRADE_DB: "true"
    networks:
      database:
    user: 1000:1000
    deploy:
      resources:
        limits:
          memory: ${LIBRECHAT_MEILISEARCH_MEM_LIMIT:-1g}
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

  mongodb:
    image: mongo:8@sha256:5211c51171f57ae60842b11664bb244628971b3d35325762a97888337b9bb0db
    container_name: LibreChat_mongodb
    volumes:
      - /opt/docker/librechat/data-node:/data/db
    environment:
      GLIBC_TUNABLES: glibc.pthread.rseq=1
    networks:
      database:
    command: mongod --noauth
    user: 1000:1000
    deploy:
      resources:
        limits:
          memory: ${LIBRECHAT_MONGODB_MEM_LIMIT:-1g}
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

  rag-api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest@sha256:f9f34c8ed6884b0ff9b17387e6174fed737dba29f21622ecb75604d82bc47bf8
    container_name: LibreChat_rag-api
    depends_on:
      - vectordb
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
    env_file: .env
    networks:
      default:
      database:
    deploy:
      resources:
        limits:
          memory: ${LIBRECHAT_RAG_API_MEM_LIMIT:-3g}
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

  vectordb:
    image: pgvector/pgvector:pg16@sha256:ccc6e83d6e35e931dc7c5def2022729d5a6c370318d099181995567ff1fb4d6b
    container_name: LibreChat_vectordb
    volumes:
      - /opt/docker/librechat/pgdata/:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB:?database name required}
      POSTGRES_USER: ${POSTGRES_USER:?database username required}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?database password required}
    networks:
      database:
    deploy:
      resources:
        limits:
          memory: ${LIBRECHAT_VECTORDB_MEM_LIMIT:-1g}
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

networks:
  database:
    internal: true
