---
services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.5.6-rootless@sha256:de832f85c00823594b2e056da1db4cd7d2d99ce2e0a997c870cc7c1749e3c731
    container_name: uptime-kuma
    volumes:
      - /opt/docker/uptime-kuma/:/app/data/
    networks:
      - pangolin
    deploy:
      resources:
        limits:
          memory: ${UPTIME_KUMA_MEM_LIMIT:-512m}
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

networks:
  pangolin:
    external: true
    name: pangolin
