---
services:
  omada-controller:
    image: mbentley/omada-controller:6.3.0.45@sha256:c87f93c2915fd0e03fe61d19fa05301c58e71c5bcd113f33801229ab19c6b4af
    container_name: omada-controller
    volumes:
      - /opt/docker/omada/data/:/opt/tplink/EAPController/data/
      - /opt/docker/omada/logs/:/opt/tplink/EAPController/logs/
    env_file: .env
    ports:
      - '8043:8043'
      - '8088:8088'
      - '8843:8843'
      - '19810:19810/udp'
      - '27001:27001/udp'
      - '29810:29810/udp'
      - '29811-29817:29811-29817'
    deploy:
      resources:
        limits:
          memory: ${OMADA_CONTROLLER_MEM_LIMIT:-2g}
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
    stop_grace_period: 60s
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
