---
services:
  pangolin:
    image: fosrl/pangolin:1.22.2@sha256:83a55f933b4d970da85333ba9715a36550972398939ba1b70fe0381434259b96
    container_name: pangolin
    volumes:
      - /opt/docker/pangolin/:/app/config/
    extra_hosts:
      - authentik.${PUBLIC_DOMAIN}:${PANGOLIN_GATEWAY_IP:-172.20.0.251}
      - git.${PUBLIC_DOMAIN}:${PANGOLIN_GATEWAY_IP:-172.20.0.251}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3001/api/v1/" ]
      interval: "3s"
      timeout: "3s"
      retries: 15
    deploy:
      resources:
        limits:
          memory: ${PANGOLIN_MEM_LIMIT:-1g}
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

  # gerbil:
  #   extends:
  #     file: ../../_common/base.yaml
  #     service: x-defaults
  #   image: fosrl/gerbil:1.0.0@sha256:ca0839f1cf41d5d9ec23ba6b2c43e725505e2cc7e1728cee9dbbcfb98e0f1659
  #   container_name: gerbil
  #   depends_on:
  #     pangolin:
  #       condition: service_healthy
  #   command:
  #     - --reachableAt=http://gerbil:3003
  #     - --generateAndSaveKeyTo=/var/config/key
  #     - --remoteConfig=http://pangolin:3001/api/v1/gerbil/get-config
  #     - --reportBandwidthTo=http://pangolin:3001/api/v1/gerbil/receive-bandwidth
  #   volumes:
  #     - "/opt/docker/pangolin/:/var/config/"
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_MODULE
  #   ports:
  #     - "51820:51820/udp"
  #     - "443:443"
  #     - "80:80"
  #   networks:
  #     default:
  #       ipv4_address: ${PANGOLIN_GATEWAY_IP:-172.20.0.251}

  traefik:
    image: traefik:v3.7.13@sha256:f86a2cab1b5c649070c49f883c743dd32d8485a56e3368c5f93b9e91f1e91259
    container_name: traefik
    depends_on:
      pangolin:
        condition: service_healthy
        restart: true
    volumes:
      - /opt/docker/pangolin/traefik/:/etc/traefik/:ro
      - /opt/docker/pangolin/letsencrypt/:/letsencrypt/
      - /opt/docker/pangolin/traefik/logs/:/var/log/traefik/
    env_file: .env
    # network_mode: service:gerbil
    ports:
      - '80:80'
      - '443:443'
      - '6697:6697/tcp'
      - '6697:6697/udp'
      - '8883:8883/tcp'
    networks:
      default:
        ipv4_address: ${PANGOLIN_GATEWAY_IP:-172.20.0.251}
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    deploy:
      resources:
        limits:
          memory: ${TRAEFIK_MEM_LIMIT:-1g}
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

networks:
  default:
    driver: bridge
    name: pangolin
    ipam:
      config:
        - subnet: 172.20.0.0/24
