---
services:
  browser-sockpuppet-chrome:
    image: dgtlmoon/sockpuppetbrowser:latest@sha256:f166a963b550c29af465c2fac518212e7e3a75f14f0d2b840cf4b79677295764
    container_name: browser-sockpuppet-chrome
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - MAX_CONCURRENT_CHROME_PROCESSES=2
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
    tmpfs:
      - /tmp:size=2g,mode=1777
    ulimits:
      core:
        soft: 0
        hard: 0

  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:0.60.4@sha256:7bb6963b730df6a1070f7a08a607b0eb7a87fe65abfa4742d876ad33bb1267eb
    container_name: changedetection
    depends_on:
      - browser-sockpuppet-chrome
    volumes:
      - /opt/docker/changedetection/:/datastore/
    environment:
      - PLAYWRIGHT_DRIVER_URL=ws://browser-sockpuppet-chrome:3000
      - FETCH_WORKERS=2
    env_file: .env
    ports:
      - '5000:5000'
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

  flareproxy:
    image: mickey3721/flareproxy:latest@sha256:5d6b4ea0c6b9024a6de9933e18fe068f2a92504e5a41d3212036cf519885bbc3
    container_name: flareproxy
    depends_on:
      flaresolverr:
        condition: service_started
    environment:
      - FLARESOLVERR_URL=http://flaresolverr:8191/v1
      - TZ=${TZ}
    expose:
      - '8080'
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

  flaresolverr:
    image: ghcr.io/thephaseless/byparr:3.0.4@sha256:874f719518f617d03a60e03411fc5d090647e1a877041e81f8dc965927c7deb6
    extends:
      file: ../../_common/base.yaml
      service: x-byparr
