---
services:
  browser-sockpuppet-chrome:
    image: dgtlmoon/sockpuppetbrowser:0.0.3@sha256:23a7be698216407648b6c78fc55de0411bde550635edc30347373c86a5176fad
    container_name: browser-sockpuppet-chrome
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - MAX_CONCURRENT_CHROME_PROCESSES=10
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
    tmpfs:
      - /tmp:size=2g,mode=1777
    ulimits:
      core:
        soft: 0
        hard: 0

  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io:0.60.3@sha256:ecacd9fd0c664a786b77daadbbbf51373519b29178a32df3ddbc5c594bc067ed
    container_name: changedetection
    depends_on:
      - browser-sockpuppet-chrome
    volumes:
      - /opt/docker/changedetection/:/datastore/
    environment:
      - PLAYWRIGHT_DRIVER_URL=ws://browser-sockpuppet-chrome:3000
    env_file: .env
    ports:
      - '5000:5000'
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

  flareproxy:
    image: mickey3721/flareproxy:latest@sha256:5d6b4ea0c6b9024a6de9933e18fe068f2a92504e5a41d3212036cf519885bbc3
    container_name: flareproxy
    depends_on:
      flaresolverr:
        condition: service_started
    environment:
      - FLARESOLVERR_URL=http://flaresolverr:8191/v1
      - TZ=${TZ}
    expose:
      - '8080'
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

  flaresolverr:
    extends:
      file: ../../_common/base.yaml
      service: x-byparr
