---
services:
  newt:
    image: fosrl/newt:1.15.0@sha256:d69d047c816ca7721eae90d5f3cd3be53b615b3d498678be21488d666538ee5c
    container_name: newt
    env_file: .env
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

networks:
  default:
    enable_ipv6: true
