---
services:
  newt:
    image: fosrl/newt:1.17.0@sha256:3465d85200cceb0f46dad8e63a40b69ec043a81df66ed0c514714302e9b83dde
    container_name: newt
    env_file: .env
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

networks:
  default:
    enable_ipv6: true
