---
services:
  postgresql:
    image: pgautoupgrade/pgautoupgrade:18-alpine@sha256:5d287ede0df43f7f448b7e56f8c4f6a79197318b15d90254a9d6a85eb7686fb0
    container_name: qui_postgres
    volumes:
      - /opt/docker/qui/database/:/var/lib/postgresql/
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-qui}
      POSTGRES_DB: ${PG_DB:-qui}
    extends:
      file: ../../_common/base.yaml
      service: x-postgres

  qui:
    image: ghcr.io/autobrr/qui:v1.25.0@sha256:3285c52f0258645d1d5a1684e25596c7355ef525363f0f9464d1c7b2cad14be8
    container_name: qui
    depends_on:
      postgresql:
        condition: service_healthy
    volumes:
      - /opt/docker/qui/config/:/config/
      - /mnt/data/:/data/
      - /mnt/data2/:/data2/
      - /mnt/data3/:/data3/
    env_file: .env
    ports:
      - '7476:7476'
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
