---
services:
  postgresql:
    image: pgautoupgrade/pgautoupgrade:18-alpine@sha256:2426484c3efdd6b7d67fe9e111017a4a1722367340197465de8fb2167238f2e2
    container_name: qui_postgres
    volumes:
      - /opt/docker/qui/database/:/var/lib/postgresql/
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-qui}
      POSTGRES_DB: ${PG_DB:-qui}
    extends:
      file: ../../_common/base.yaml
      service: x-postgres

  qui:
    image: ghcr.io/autobrr/qui:v1.31.1@sha256:01bb5ad8786bc57ff4e90a541b7b75e6a1ec207614222908151beed1e22ad6e3
    container_name: qui
    depends_on:
      postgresql:
        condition: service_healthy
    volumes:
      - /opt/docker/qui/config/:/config/
      - /mnt/data/:/data/
      - /mnt/data2/:/data2/
      - /mnt/data3/:/data3/
    env_file: .env
    ports:
      - '7476:7476'
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
