---
x-komf-base: &komf-base
  extends:
    file: ../../_common/base.yaml
    service: x-defaults
  image: ghcr.io/loocool2/komf:latest@sha256:1b7645b6080364c9519f61c91236515be827bae2b409fbe450d6bee50f9ed38b
  environment:
    KOMF_LOG_LEVEL: INFO
    TZ: ${TZ:-UTC}
    JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -XX:ShenandoahGuaranteedGCInterval=3600000 -XX:TrimNativeHeapInterval=3600000
  user: "${PUID:-1000}:${PGID:-1000}"
x-vol-media: &vol-media /mnt/data3/media:/data3/media

services:
  komf:
    container_name: komf
    volumes:
      - *vol-media
      - /opt/docker/komf/:/config/
    ports:
      - '8085:8085'
    <<: *komf-base

  komf2:
    container_name: komf2
    volumes:
      - *vol-media
      - /opt/docker/komf2/:/config/
    ports:
      - '8086:8085'
    <<: *komf-base
