---
x-komf-base: &komf-base
  extends:
    file: ../../_common/base.yaml
    service: x-defaults
  image: sndxr/komf:2.1.0@sha256:373580779e2e75d4e00e2f05859f789e05691c54600ca83d1cb528f0aad1f7b6
  environment:
    KOMF_LOG_LEVEL: INFO
    TZ: ${TZ:-UTC}
    JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -XX:ShenandoahGuaranteedGCInterval=3600000 -XX:TrimNativeHeapInterval=3600000
  user: "${PUID:-1000}:${PGID:-1000}"
x-vol-media: &vol-media /mnt/data3/media:/data3/media

services:
  komf:
    container_name: komf
    volumes:
      - *vol-media
      - /opt/docker/komf/:/config/
    ports:
      - '8085:8085'
    <<: *komf-base

  komf2:
    container_name: komf2
    volumes:
      - *vol-media
      - /opt/docker/komf2/:/config/
    ports:
      - '8086:8085'
    <<: *komf-base
