---
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:2.1.5@sha256:26cfac865d0924afc7f1e34a65e34e41c22f7b6b61d0c23a6aaebad13104b113
    container_name: syncthing-${HOSTNAME}
    volumes:
      - /opt/docker/syncthing-${HOSTNAME}/:/config/
      - ${SYNC_PATH}:${SYNC_PATH}
    env_file: .env
    network_mode: host
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
    hostname: ${HOSTNAME}
