---
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:2.1.3@sha256:07da4c778027cb13d4a2b9bb8b8d7432ac3a0f0540bb7248b016be3a1cc69788
    container_name: syncthing-${HOSTNAME}
    volumes:
      - /opt/docker/syncthing-${HOSTNAME}/:/config/
      - ${SYNC_PATH}:${SYNC_PATH}
    env_file: .env
    network_mode: host
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
    hostname: ${HOSTNAME}
