---
x-profilarr-base: &profilarr-base
  extends:
    file: ../../_common/base.yaml
    service: x-defaults
  image: ghcr.io/dictionarry-hub/profilarr:2.1.0@sha256:75a43c9c19c70f6e48315d4ed5cef3232d905da8fab397391a2078a5e0fd7ec1
  env_file: .env
  environment: &profilarr-env
    PARSER_HOST: parser
    PARSER_PORT: 5000
  depends_on:
    parser:
      condition: service_healthy
  init: true

services:
  parser:
    image: ghcr.io/dictionarry-hub/profilarr-parser:2.1.0@sha256:83d668258b2a798adaf25dec0d78e5159953c3b015e2d31edb8e5b9859f3c591
    container_name: profilarr-parser
    expose:
      - '5000'
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
    init: true

  profilarr-anime:
    container_name: profilarr-anime
    volumes:
      - /opt/docker/profilarr-anime/:/config/
    environment:
      <<: *profilarr-env
      ORIGIN: https://profilarr-anime.${PUBLIC_DOMAIN}
    ports:
      - '6868:6868'
    <<: *profilarr-base

  profilarr-tv:
    container_name: profilarr-tv
    volumes:
      - /opt/docker/profilarr-tv/:/config/
    environment:
      <<: *profilarr-env
      ORIGIN: https://profilarr-tv.${PUBLIC_DOMAIN}
    ports:
      - '6869:6868'
    <<: *profilarr-base
