---
services:
  music-assistant-server:
    image: ghcr.io/music-assistant/server:2.9.11@sha256:dd0605ba528af46bb1c36ceb71fa57f5e9b23d10ec2fff787bd16495271f5681
    container_name: music-assistant-server
    volumes:
      - /opt/docker/music-assistant-server/:/data/
    env_file: .env
    network_mode: host # Network mode must be set to host for MA to work correctly
    user: 1000:1000
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
