---
services:
  music-assistant-server:
    image: ghcr.io/music-assistant/server:2.9.12@sha256:1d77137a750e20975650eae4b02333830ae8306da9bf23da193a391813db4e77
    container_name: music-assistant-server
    volumes:
      - /opt/docker/music-assistant-server/:/data/
    env_file: .env
    network_mode: host # Network mode must be set to host for MA to work correctly
    user: 1000:1000
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
