---
services:
  museum:
    image: ghcr.io/ente-io/server@sha256:c56831e83306988b2f5ee30eee20194d6b8f848a9cc4f4afa75931722ac1086b
    container_name: ente_museum
    # ports:
    #   - 8080:8080 # API
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - /opt/docker/ente/museum.yaml:/museum.yaml:ro
      - /opt/docker/ente/data/:/data/:ro
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER:-pguser}
      POSTGRES_DB: ${PG_DB:-ente_db}
    env_file: .env
    # Resolve "localhost:3200" in the museum container to the minio container.
    # socat:
    #   image: alpine/socat
    #   network_mode: service:museum
    #   depends_on: [museum]
    #   command: "TCP-LISTEN:3200,fork,reuseaddr TCP:minio:3200"
    networks:
      - default
      - pangolin
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

  postgres:
    image: pgautoupgrade/pgautoupgrade:18-alpine@sha256:19f988b90c8d0ad9c7edd70cf23c83e069abd8a57f0fdce0373588ddaf189894
    container_name: ente_postgres
    volumes:
      - /opt/docker/ente/postgres-data/:/var/lib/postgresql/
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-pguser}
      POSTGRES_DB: ${PG_DB:-ente_db}
    networks:
      - default
    extends:
      file: ../../_common/base.yaml
      service: x-postgres

  web:
    image: ghcr.io/ente-io/web@sha256:94d76dae2ec6e767a86fa93da4c23243cd93f27295e82c51205bc137a4204dab
    container_name: ente_web
    # ports:
    #   - 3000:3000 # Photos web app
    #   - 3001:3001 # Accounts
    #   - 3002:3002 # Public albums
    #   - 3003:3003 # Auth
    #   - 3004:3004 # Cast
    networks:
      - default
      - pangolin
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

networks:
  default:
    driver: bridge
  pangolin:
    external: true
    name: pangolin
