---
services:
  museum:
    image: ghcr.io/ente/server@sha256:e9e06eb01834c38f41a3a09f9a64885b631346ce0005ccff2153faea403bd6e2
    container_name: ente_museum
    # ports:
    #   - 8080:8080 # API
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - /opt/docker/ente/museum.yaml:/museum.yaml:ro
      - /opt/docker/ente/data/:/data/:ro
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER:-pguser}
      POSTGRES_DB: ${PG_DB:-ente_db}
    env_file: .env
    # Resolve "localhost:3200" in the museum container to the minio container.
    # socat:
    #   image: alpine/socat
    #   network_mode: service:museum
    #   depends_on: [museum]
    #   command: "TCP-LISTEN:3200,fork,reuseaddr TCP:minio:3200"
    networks:
      - default
      - pangolin
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

  postgres:
    image: pgautoupgrade/pgautoupgrade:18-alpine@sha256:9e3d1652279f10754539a628eea1dc1052653ffa8bfd174147a983c57067c425
    container_name: ente_postgres
    volumes:
      - /opt/docker/ente/postgres-data/:/var/lib/postgresql/
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-pguser}
      POSTGRES_DB: ${PG_DB:-ente_db}
    networks:
      - default
    extends:
      file: ../../_common/base.yaml
      service: x-postgres

  web:
    image: ghcr.io/ente/web@sha256:c8dedd75a316460c4ac2ecf1444115c3fd70544a0828e753e30052cc8013b20e
    container_name: ente_web
    # ports:
    #   - 3000:3000 # Photos web app
    #   - 3001:3001 # Accounts
    #   - 3002:3002 # Public albums
    #   - 3003:3003 # Auth
    #   - 3004:3004 # Cast
    networks:
      - default
      - pangolin
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

networks:
  default:
    driver: bridge
  pangolin:
    external: true
    name: pangolin
