---
services:
  museum:
    image: ghcr.io/ente/server@sha256:f646b68a1b8d27e3375a67e3719ed6af97e9501a81e0af9a2ec7f57ce2b3264e
    container_name: ente_museum
    # ports:
    #   - 8080:8080 # API
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - /opt/docker/ente/museum.yaml:/museum.yaml:ro
      - /opt/docker/ente/data/:/data/:ro
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-pguser}
      POSTGRES_DB: ${PG_DB:-ente_db}
    env_file: .env
    # Resolve "localhost:3200" in the museum container to the minio container.
    # socat:
    #   image: alpine/socat
    #   network_mode: service:museum
    #   depends_on: [museum]
    #   command: "TCP-LISTEN:3200,fork,reuseaddr TCP:minio:3200"
    networks:
      - default
      - pangolin
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

  postgres:
    image: pgautoupgrade/pgautoupgrade:18-alpine@sha256:9b9908c5cda86e05291d00f770914ab24dcae1c657a7afe701ffe2496f997503
    container_name: ente_postgres
    volumes:
      - /opt/docker/ente/postgres-data/:/var/lib/postgresql/
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-pguser}
      POSTGRES_DB: ${PG_DB:-ente_db}
    networks:
      - default
    extends:
      file: ../../_common/base.yaml
      service: x-postgres

  web:
    image: ghcr.io/ente/web@sha256:d40a0df0df283cbbb1e7b20e5b98839d80666f83c12d37c8f174974841c67d00
    container_name: ente_web
    # ports:
    #   - 3000:3000 # Photos web app
    #   - 3001:3001 # Accounts
    #   - 3002:3002 # Public albums
    #   - 3003:3003 # Auth
    #   - 3004:3004 # Cast
    networks:
      - default
      - pangolin
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

networks:
  default:
    driver: bridge
  pangolin:
    external: true
    name: pangolin
