---
services:
  database.postgres:
    image: pgautoupgrade/pgautoupgrade:18-alpine@sha256:2426484c3efdd6b7d67fe9e111017a4a1722367340197465de8fb2167238f2e2
    container_name: chaptarr_postgres
    volumes:
      - /opt/docker/chaptarr/db/:/var/lib/postgresql/
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-chaptarr}
      POSTGRES_DB: ${PG_DB:-chaptarr-main}
    extends:
      file: ../../_common/base.yaml
      service: x-postgres

  service.chaptarr:
    image: chaptarr/chaptarr:0.9.965@sha256:bb00d67cbe1485d1cd61ef178362a29b42aa08f86b290841aab4b115ad2647a6
    container_name: chaptarr
    depends_on:
      database.postgres:
        condition: service_healthy
    volumes:
      - /opt/docker/chaptarr/config/:/config/
      - /mnt/data2/:/data2/ # :ro
    environment:
      Chaptarr__Postgres__Host: database.postgres
      Chaptarr__Postgres__Port: 5432
      Chaptarr__Postgres__User: ${PG_USER:-chaptarr}
      Chaptarr__Postgres__Password: ${PG_PASS:?database password required}
      Chaptarr__Postgres__MainDb: ${PG_DB:-chaptarr-main}
      Chaptarr__Postgres__LogDb: chaptarr-log
      Chaptarr__Postgres__CacheDb: chaptarr-cache
    env_file: .env
    ports:
      - '8789:8789'
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
