---
services:
  database.postgres:
    image: pgautoupgrade/pgautoupgrade:18-alpine@sha256:60580d98bb0c948efcd628d322091e965c1493ea6ccc4325ce22fc4dbd4dfa38
    container_name: chaptarr_postgres
    volumes:
      - /opt/docker/chaptarr/db/:/var/lib/postgresql/
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-chaptarr}
      POSTGRES_DB: ${PG_DB:-chaptarr-main}
    extends:
      file: ../../_common/base.yaml
      service: x-postgres

  service.chaptarr:
    image: chaptarr/chaptarr:0.9.936@sha256:e7aa84d7d65c460c914d36438529592181dca9c60146efdd4914a8baad2953be
    container_name: chaptarr
    depends_on:
      database.postgres:
        condition: service_healthy
    volumes:
      - /opt/docker/chaptarr/config/:/config/
      - /mnt/data2/:/data2/ # :ro
    environment:
      Chaptarr__Postgres__Host: database.postgres
      Chaptarr__Postgres__Port: 5432
      Chaptarr__Postgres__User: ${PG_USER:-chaptarr}
      Chaptarr__Postgres__Password: ${PG_PASS:?database password required}
      Chaptarr__Postgres__MainDb: ${PG_DB:-chaptarr-main}
      Chaptarr__Postgres__LogDb: chaptarr-log
      Chaptarr__Postgres__CacheDb: chaptarr-cache
    env_file: .env
    ports:
      - '8789:8789'
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
