---
services:
  beszel:
    image: henrygd/beszel:0.21.0@sha256:6b39a8b64f9b15d00a25e7683e31a93c46161182a54f62713525107064e10599
    container_name: beszel
    volumes:
      - /opt/docker/beszel/:/beszel_data/
    env_file: .env
    networks:
      - pangolin
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

networks:
  pangolin:
    external: true
    name: pangolin
