---
services:
  beszel:
    image: henrygd/beszel:0.18.8@sha256:4c51486968efa0b0a702c1b0967966a2e06fb250b7418f3072d2488faea27c51
    container_name: beszel
    volumes:
      - /opt/docker/beszel/:/beszel_data/
    env_file: .env
    networks:
      - pangolin
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

networks:
  pangolin:
    external: true
    name: pangolin
