---
services:
  beszel:
    image: henrygd/beszel:0.20.0@sha256:897e807a065adf8e89e30ae0cd79d1f5e38fe84ccaffbc418bde9d3cdca4eacc
    container_name: beszel
    volumes:
      - /opt/docker/beszel/:/beszel_data/
    env_file: .env
    networks:
      - pangolin
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

networks:
  pangolin:
    external: true
    name: pangolin
