---
services:
  birdnet-go:
    image: ghcr.io/tphakala/birdnet-go:20260823@sha256:233b94f1d3b27b261ec8d997364db0cb953f3e3b3362a89e9e22ad4a589143d6
    container_name: birdnet-go
    volumes:
      - /opt/docker/birdnet/config/:/config/
      - /opt/docker/birdnet/data/:/data/
    env_file: .env
    ports:
      - '8080:8080'
    deploy:
      resources:
        limits:
          memory: ${BIRDNET_MEM_LIMIT:-2g}
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
    tmpfs:
      - /config/hls/:exec,size=50M,uid=${BIRDNET_UID:-1000},gid=${BIRDNET_GID:-1000},mode=0755 # Mount HLS stream segment files directory as tmpfs (RAM disk)
