---
services:
  birdnet-go:
    image: ghcr.io/tphakala/birdnet-go:20260716@sha256:b6382049967374b49a62ada386a6551efc3806a56c77934cd1bdf300d5c55878
    container_name: birdnet-go
    volumes:
      - /opt/docker/birdnet/config/:/config/
      - /opt/docker/birdnet/data/:/data/
    env_file: .env
    ports:
      - '8080:8080'
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
    mem_limit: ${BIRDNET_MEM_LIMIT:-2g}
    tmpfs:
      - /config/hls/:exec,size=50M,uid=${BIRDNET_UID:-1000},gid=${BIRDNET_GID:-1000},mode=0755 # Mount HLS stream segment files directory as tmpfs (RAM disk)
