---
services:
  birdnet-go:
    image: ghcr.io/tphakala/birdnet-go:20261010@sha256:d412e7cc07cd77e7a1ef9d91fbffad1428106277a745c5accd90904a7cfb8b73
    container_name: birdnet-go
    volumes:
      - /opt/docker/birdnet/config/:/config/
      - /opt/docker/birdnet/data/:/data/
      - type: bind
        source: /mnt/appdata/birdnet/clips
        target: /data/clips
        bind:
          create_host_path: false
    env_file: .env
    ports:
      - '8080:8080'
    deploy:
      resources:
        limits:
          memory: ${BIRDNET_MEM_LIMIT:-2g}
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
    tmpfs:
      - /config/hls/:exec,size=50M,uid=${BIRDNET_UID:-1000},gid=${BIRDNET_GID:-1000},mode=0755 # Mount HLS stream segment files directory as tmpfs (RAM disk)
