---
services:
  flaresolverr:
    extends:
      file: ../../_common/base.yaml
      service: x-byparr

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.6.0-develop@sha256:2df9ae57c475bf4341abd833e56a9268bb02167cc5f3f828a8347d2d8628f652
    container_name: prowlarr
    volumes:
      - /opt/docker/prowlarr/:/config
    env_file: .env
    ports:
      - '9696:9696'
    healthcheck:
      test: [ "CMD-SHELL", "curl -fSs http://localhost:9696/ping || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
