---
services:
  flaresolverr:
    extends:
      file: ../../_common/base.yaml
      service: x-byparr

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.6.1-develop@sha256:dcb53158072c700ab578e6f89d5b4d6efd784e74496e567f98bfa96cd1db3a31
    container_name: prowlarr
    volumes:
      - /opt/docker/prowlarr/:/config
    env_file: .env
    ports:
      - '9696:9696'
    healthcheck:
      test: [ "CMD-SHELL", "curl -fSs http://localhost:9696/ping || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
