---
services:
  flaresolverr:
    extends:
      file: ../../_common/base.yaml
      service: x-byparr

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.6.3-develop@sha256:363769676eb4a58dc5f691fb95ff65b3ed6918654b90c15c676c988aa2921048
    container_name: prowlarr
    volumes:
      - /opt/docker/prowlarr/:/config
    env_file: .env
    ports:
      - '9696:9696'
    healthcheck:
      test: [ "CMD-SHELL", "curl -fSs http://localhost:9696/ping || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
