---
services:
  kavita:
    image: lscr.io/linuxserver/kavita:0.9.1@sha256:6c5dc34fe5a0d8615d530aa24f550cbbf9304ab4b352f7f9fa6133510b93e6bf
    container_name: kavita
    volumes:
      - /opt/docker/kavita/:/config/
      - /mnt/data3/media/:/data3/media/
      - /mnt/data3/torrents/:/data3/torrents/
      - /mnt/data2/torrents/manga/:/data2/torrents/manga/
    env_file: .env
    ports:
      - '5000:5000'
    deploy:
      resources:
        limits:
          memory: ${KAVITA_MEM_LIMIT:-2g}
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
