---
services:
  kavita:
    image: lscr.io/linuxserver/kavita:0.9.0@sha256:7e3be67100797e264756e9a1a9c6dd821c5dc0950b7940a645a629a429831118
    container_name: kavita
    volumes:
      - /opt/docker/kavita/:/config/
      - /mnt/data3/media/:/data3/media/
      - /mnt/data3/torrents/:/data3/torrents/
      - /mnt/data2/torrents/manga/:/data2/torrents/manga/
    env_file: .env
    ports:
      - '5000:5000'
    deploy:
      resources:
        limits:
          memory: ${KAVITA_MEM_LIMIT:-2g}
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
