---
services:
  chrome:
    image: ghcr.io/karakeep-app/karakeep-chrome:151.0.7922.47-r1@sha256:5b19bbb160e9ff60681a3abd97e1c4ec9f64212301410de658c3900ab7ef31e7
    command:
      - --disable-gpu
      - --disable-dev-shm-usage
      - --hide-scrollbars
      - --disable-blink-features=AutomationControlled
      - --window-size=1440,900
    deploy:
      resources:
        limits:
          memory: ${KARAKEEP_CHROME_MEM_LIMIT:-1g}
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
    init: true

  meilisearch:
    image: getmeili/meilisearch:v1.53.1@sha256:8d6643d86d71fad6ad3cba92cde7ccfce9e4d6c384bda67598eb553571c32431
    volumes:
      - /opt/docker/karakeep/meilisearch/:/meili_data/
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:?master key required}
      MEILI_NO_ANALYTICS: "true"
      MEILI_UPGRADE_DB: "true"
    user: 1000:1000
    deploy:
      resources:
        limits:
          memory: ${KARAKEEP_MEILISEARCH_MEM_LIMIT:-1g}
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

  web:
    image: ghcr.io/karakeep-app/karakeep:0.33.2@sha256:b069e4307dec06ea06d16989c6861c30a1ff208568be44ed5fb5d422cd3e950c
    volumes:
      - /opt/docker/karakeep/data/:/data/
      - /assets/:/assets/
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data # DON'T CHANGE THIS
    env_file: .env
    ports:
      - '3000:3000'
    deploy:
      resources:
        limits:
          memory: ${KARAKEEP_MEM_LIMIT:-1g}
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
