---
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main@sha256:6a773e5c3a246b65cbe74ce942b294292c0e5f81c138f703d111bc162f7d7c3d
    container_name: openwebui
    volumes:
      - /opt/docker/open-webui/:/app/backend/data/
    env_file: .env
    ports:
      - '3000:8080'
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
    mem_limit: ${OPENWEBUI_MEM_LIMIT:-2g}
