---
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main@sha256:8afd2d774834c618a75411b3491cdc5da7396dc464f56a160b937ff2992eb6e4
    container_name: openwebui
    volumes:
      - /opt/docker/open-webui/:/app/backend/data/
    env_file: .env
    ports:
      - '3000:8080'
    deploy:
      resources:
        limits:
          memory: ${OPENWEBUI_MEM_LIMIT:-2g}
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
