---
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main@sha256:5c0d8f6d58ea276204b927205e43850689799f25420a67079cb988df2cf865cf
    container_name: openwebui
    volumes:
      - /opt/docker/open-webui/:/app/backend/data/
    env_file: .env
    ports:
      - '3000:8080'
    deploy:
      resources:
        limits:
          memory: ${OPENWEBUI_MEM_LIMIT:-2g}
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
