---
services:
  database.postgres:
    image: pgautoupgrade/pgautoupgrade:18-alpine@sha256:9c832ef7ae1cee9c8c5c678f0229871c83941ff5c7a25f910ee7e9a8f2768620
    container_name: semaphore_postgres
    volumes:
      - /opt/docker/semaphore/db/:/var/lib/postgresql/
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-semaphore}
      POSTGRES_DB: ${PG_DB:-semaphore}
    ports:
      - '127.0.0.1:5432:5432'
    extends:
      file: ../../_common/base.yaml
      service: x-postgres

  service.semaphore:
    image: semaphoreui/semaphore:v2.19.12@sha256:3996804607ebb63690528185bb9adc3507ee896851098e4453975f2ce7f8b435
    container_name: semaphore
    depends_on:
      database.postgres:
        condition: service_healthy
    volumes:
      - /opt/docker/semaphore/tmp/:/tmp/semaphore/
    environment:
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB_HOST: 127.0.0.1
      SEMAPHORE_DB_NAME: ${PG_DB:-semaphore}
      SEMAPHORE_DB_USER: ${PG_USER:-semaphore}
      SEMAPHORE_DB_PASS: ${PG_PASS:?database password required}
    env_file: .env
    network_mode: host
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
