---
services:
  maintainerr:
    image: ghcr.io/maintainerr/maintainerr:3.26.0@sha256:0ff47e2465704ceb90cd79a1516844bc1c74f6c8eef8317988618a01e5a680ea
    container_name: maintainerr
    volumes:
      - /opt/docker/maintainerr/:/opt/data/
    env_file: .env
    ports:
      - '6246:6246'
    user: 1000:1000
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
