---
services:
  maintainerr:
    image: ghcr.io/maintainerr/maintainerr:3.29.0@sha256:7487d374290e59add65407ec295629e489f9057dbf18e2a9dff70d6201ffb6f9
    container_name: maintainerr
    volumes:
      - /opt/docker/maintainerr/:/opt/data/
    env_file: .env
    ports:
      - '6246:6246'
    user: 1000:1000
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
