---
services:
  maintainerr:
    image: ghcr.io/maintainerr/maintainerr:3.23.0@sha256:b6ec7216c5032dd1b8a3aeab8babd167dbeb0794b531fe01fd90b013915db093
    container_name: maintainerr
    volumes:
      - /opt/docker/maintainerr/:/opt/data/
    env_file: .env
    ports:
      - '6246:6246'
    user: 1000:1000
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
