---
services:
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy:v0.5.0@sha256:1f5038b54f06c3e18422902cf00ba21803d1c97805aae032e5e6673d532d3459
    container_name: fileflows_docker-socket-proxy
    environment:
      CONTAINERS: 1
      IMAGES: 1
      NETWORKS: 1
      VOLUMES: 1
      POST: 1
      INFO: 1
    networks:
      - socket_proxy
    extends:
      file: ../../_common/base.yaml
      service: x-docker-socket-proxy

  fileflows:
    image: revenz/fileflows:26.09@sha256:5d7460ec63be60bb33fd50336b064c138e7d005a8fd3d19d47ff259de7df8b82
    depends_on:
      - docker-socket-proxy
    volumes:
      - /opt/docker/fileflows/data/:/app/Data/
      - /opt/docker/fileflows/logs/:/app/Logs/
      - /opt/docker/fileflows/common/:/app/common/
      - /mnt/data/:/data/
      - /mnt/data2/:/data2/
      - /mnt/data3/:/data3/
      - type: tmpfs
        target: /temp/
        tmpfs:
          size: 2000000000
    environment:
      DOCKER_HOST: tcp://docker-socket-proxy:2375
    env_file: .env
    ports:
      - '19200:5000'
    networks:
      default:
      socket_proxy:
    deploy:
      resources:
        limits:
          memory: ${FILEFLOWS_MEM_LIMIT:-4g}
    devices:
      - /dev/dri:/dev/dri/
    extends:
      file: ../../_common/base.yaml
      service: x-runtime-defaults
    security_opt:
      - no-new-privileges:false

networks:
  socket_proxy:
    driver: bridge
    internal: true
