---
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2026.8.2@sha256:56690a89c79a0de98035e1719f8324a92d5859c1192ff45adb0230ea81cb42a5
    container_name: homeassistant
    volumes:
      - /opt/docker/home-assistant/:/config/
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus/:/run/dbus/:ro
    network_mode: host
    deploy:
      resources:
        limits:
          memory: ${HOMEASSISTANT_MEM_LIMIT:-1g}
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

  matter-server:
    image: ghcr.io/matter-js/python-matter-server:8.1.2@sha256:6827e352011e2d8c2bde771e446fcf72acc49150ef66bad978816bac1762aad3
    container_name: matter-server
    volumes:
      - /opt/docker/matter-server/:/data/
      # - /run/dbus:/run/dbus:ro # Required for Bluetooth via D-Bus
    network_mode: host
    deploy:
      resources:
        limits:
          memory: ${MATTER_SERVER_MEM_LIMIT:-1g}
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
