---
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2026.8.1@sha256:6340a3de3917a9b19368e767310a96dd090f6a19aca8aeadf87fd1145cec9682
    container_name: homeassistant
    volumes:
      - /opt/docker/home-assistant/:/config/
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus/:/run/dbus/:ro
    network_mode: host
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
    mem_limit: ${HOMEASSISTANT_MEM_LIMIT:-1g}

  matter-server:
    image: ghcr.io/matter-js/python-matter-server:8.1.2@sha256:6827e352011e2d8c2bde771e446fcf72acc49150ef66bad978816bac1762aad3
    container_name: matter-server
    volumes:
      - /opt/docker/matter-server/:/data/
      # - /run/dbus:/run/dbus:ro # Required for Bluetooth via D-Bus
    network_mode: host
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
    mem_limit: ${MATTER_SERVER_MEM_LIMIT:-1g}
