services:
  zigbee2mqtt:
    image: ghcr.io/koenkk/zigbee2mqtt:2.14.0@sha256:c13d177dd7f7f396574ab00926188ad542cfb68c6a5d5f84021bebd9adf6ede9
    container_name: zigbee2mqtt
    volumes:
      - /opt/docker/zigbee2mqtt/:/app/data/
      - /run/udev/:/run/udev/:ro
    env_file: .env
    ports:
      - '8080:8080'
    user: 1001:1001
    devices:
      - '${ZIGBEE_DEVICE}:${ZIGBEE_DEVICE}'
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
