---
services:
  matterbridge:
    image: luligu/matterbridge:3.10.8@sha256:1ec50ecd0694adfdd781a13c5df8ab6f9712925f0b5ecea9662c308b6bc35062
    container_name: matterbridge
    volumes:
      - /opt/docker/matterbridge/Matterbridge/:/root/Matterbridge/
      - /opt/docker/matterbridge/.matterbridge/:/root/.matterbridge/
      - /opt/docker/matterbridge/.mattercert/:/root/.mattercert/
    network_mode: host
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
