---
services:
  matterbridge:
    image: luligu/matterbridge:3.10.6@sha256:97e16340825c9b31f17d34f8dc47aa12251b39045705585feeed6f2d04b720ac
    container_name: matterbridge
    volumes:
      - /opt/docker/matterbridge/Matterbridge/:/root/Matterbridge/
      - /opt/docker/matterbridge/.matterbridge/:/root/.matterbridge/
      - /opt/docker/matterbridge/.mattercert/:/root/.mattercert/
    network_mode: host
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
