---
services:
  matterbridge:
    image: luligu/matterbridge:3.10.5@sha256:1216dd5f93f1c527dcd91c6098aa9d8078c9c0c35a0f302a0b53d4d77a226e1a
    container_name: matterbridge
    volumes:
      - /opt/docker/matterbridge/Matterbridge/:/root/Matterbridge/
      - /opt/docker/matterbridge/.matterbridge/:/root/.matterbridge/
      - /opt/docker/matterbridge/.mattercert/:/root/.mattercert/
    network_mode: host
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
