---
services:
  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync:v0.9.4@sha256:4fec72b9c580c6711036ea42db645232d86384fde687365b0d0452d38d507280
    container_name: adguardhome-sync
    # volumes:
    #   - /opt/adguardhome-sync/adguardhome-sync.yaml:/adguardhome-sync.yaml:ro
    env_file: .env
    ports:
      - '8080:8080'
    command: run --config /adguardhome-sync.yaml
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
