---
services:
  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync:v0.9.3@sha256:b3499852640866c5742fd72cca190f40e2741c279d60fd62b9130cd8142aafec
    container_name: adguardhome-sync
    # volumes:
    #   - /opt/adguardhome-sync/adguardhome-sync.yaml:/adguardhome-sync.yaml:ro
    env_file: .env
    ports:
      - '8080:8080'
    command: run --config /adguardhome-sync.yaml
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
