---
services:
  vaultwarden:
    image: vaultwarden/server:1.37.2@sha256:094b5689ed81549bd293418395c7cf495ae9d960fc2d4928cef2083ef913d912
    container_name: vaultwarden
    volumes:
      - /opt/docker/vaultwarden/vw-data/:/data/
    env_file: .env
    networks:
      - pangolin
    deploy:
      resources:
        limits:
          memory: ${VAULTWARDEN_MEM_LIMIT:-512m}
    extends:
      file: ../../_common/base.yaml
      service: x-defaults

networks:
  pangolin:
    external: true
    name: pangolin
