---
services:
  languagetool:
    image: erikvl87/languagetool@sha256:ef8fa12cbd485166c9ceeb7139d76d56d07707a624da6bb1fc1fbb5411750527
    container_name: languagetool
    volumes:
      - /opt/docker/languagetool/ngrams/:/ngrams/
      # - /opt/docker/languagetool/logback.xml:/LanguageTool/logback.xml:ro
    env_file: .env
    ports:
      - '8010:8010'
    deploy:
      resources:
        limits:
          memory: ${LANGUAGETOOL_MEM_LIMIT:-2g}
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
