---
services:
  rustic:
    image: ghcr.io/rustic-rs/rustic:v0.11.4@sha256:bb8e60aef240ca54ea1091f42f07d48f552edf8474062e55b5c72e7cdf3a9949
    container_name: rustic
    volumes:
      - /opt/docker/rustic/config/:/.config/rustic/:ro
      - /opt/docker/rustic/cache/:/.cache/rustic/
      - /opt/docker/rustic/curl:/curl
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro
      - /mnt/data/:/mnt/data/:ro
      - /mnt/data2/:/mnt/data2/:ro
      - /mnt/data3/:/mnt/data3/:ro
    env_file: .env
    command: backup
    restart: "no"
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
