---
services:
  cloudflare-ddns-real:
    image: favonia/cloudflare-ddns:1.17.1@sha256:5e61736b982b87d84a1120b4767c4deff0f2cc55ca3ee9dcb1dc58623039b5cb
    env_file: .env
    network_mode: host
    cap_add:
      - SETUID
      - SETGID
    cap_drop:
      - all
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
    read_only: true
