---
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.37.1@sha256:581d68b2a6fc7ebf58d81c878a9f387cbbc0d88ac9d37b298b9cee10168af85b
    volumes:
      - /mnt/data2/media/audiobooks/:/audiobooks/
      - /mnt/data2/media/ebooks/:/ebooks/
      - /mnt/data2/media/podcasts/:/podcasts/
      - /opt/docker/audiobookshelf/config/:/config/
      - /opt/docker/audiobookshelf/metadata/:/metadata/
    ports:
      - '13378:80'
    user: 1000:1000
    deploy:
      resources:
        limits:
          memory: ${AUDIOBOOKSHELF_MEM_LIMIT:-1g}
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
