---
services:
  beets:
    image: lscr.io/linuxserver/beets:2.13.1@sha256:844c91ba922fdb77826c09da12c0666783ffd63f9c3107e7465b0cb6774b25df
    container_name: beets
    volumes:
      - /opt/docker/beets/:/config/
      - /mnt/data3/torrents/music/:/music/:ro
    env_file: .env
    ports:
      - '8337:8337'
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
