---
services:
  beets:
    image: lscr.io/linuxserver/beets:2.13.1@sha256:90b1404e962dfc09c1926f4d8dca8920fc90d71369df5398340a12eb8ce7328c
    container_name: beets
    volumes:
      - /opt/docker/beets/:/config/
      - /mnt/data3/torrents/music/:/music/:ro
    env_file: .env
    ports:
      - '8337:8337'
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
