---
services:
  beets:
    image: lscr.io/linuxserver/beets:2.14.0@sha256:bbd09e2b19a0903f3f916c26e9ae5c30004913b293228b422154c0f9fecb2cd9
    container_name: beets
    volumes:
      - /opt/docker/beets/:/config/
      - /mnt/data3/torrents/music/:/music/:ro
    env_file: .env
    ports:
      - '8337:8337'
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
