---
services:
  qbit_manage:
    image: ghcr.io/stuffanthings/qbit_manage:v4.12.0@sha256:7a7db6bdec57baf06d580e97d44f00185ff3a774335951b0affc849e014cb8f8
    container_name: qbit_manage
    volumes:
      - /opt/docker/qbit_manage/:/config/
      - /opt/docker/qbittorrent/:/qbittorrent/:ro
      - /mnt/data/:/data/
      - /mnt/data2/:/data2/
      - /mnt/data3/:/data3/
    env_file: .env
    ports:
      - '8080:8080'
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
