---
services:
  wolf:
    image: ghcr.io/games-on-whales/wolf:stable@sha256:0d901e766e6ed288712ff994dd3b877aea7c9f22ff6e5b0efbb16bc7bb4ae9a4
    container_name: wolf
    volumes:
      - /opt/docker/wolf/:/opt/docker/wolf/
      - /opt/docker/wolf/cfg/:/etc/wolf/cfg/
      - /games/:/games/
      - /tmp/sockets/:/tmp/sockets/
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/:/dev/
      - /mnt/udev/:/run/udev/
    environment:
      - XDG_RUNTIME_DIR=/tmp/sockets
      - HOST_APPS_STATE_FOLDER=/opt/docker/wolf
    env_file: .env
    network_mode: host
    device_cgroup_rules:
      - "c 13:* rmw"
    devices:
      - /dev/dri
      - /dev/uinput
      - /dev/uhid
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
    mem_limit: ${WOLF_MEM_LIMIT:-4g}
