---
services:
  esphome:
    image: ghcr.io/esphome/esphome:2026.7.4@sha256:e636269c6390c2124916510d45f55febb1d9ce41365f8445c9083ee41e43c92b
    container_name: esphome
    volumes:
      - /opt/docker/esphome/:/config
    env_file: .env
    network_mode: host
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
