---
services:
  esphome:
    image: ghcr.io/esphome/esphome:2026.8.2@sha256:000c5ee5ee96d57208ee48f2d255f73713236f183959803e64cd0b00c39b277b
    container_name: esphome
    volumes:
      - /opt/docker/esphome/:/config
    env_file: .env
    network_mode: host
    extends:
      file: ../../_common/base.yaml
      service: x-defaults
